[versions]
kotlin = "2.3.0-Beta2"
junit-jupiter-engine = "6.0.1"
koog = "0.5.2"
serialization = "1.9.0"
ktor = "3.3.0"
logback = "1.5.21"

[libraries]
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter-engine" }
koog-agents = { module = "ai.koog:koog-agents", version.ref = "koog" }
koog-a2a-core = { module = "ai.koog:a2a-core", version.ref = "koog" }
koog-a2a-server = { module = "ai.koog:a2a-server", version.ref = "koog" }
koog-a2a-client = { module = "ai.koog:a2a-client", version.ref = "koog" }
koog-a2a-transport-server = { module = "ai.koog:a2a-transport-server-jsonrpc-http", version.ref = "koog" }
koog-a2a-transport-client = { module = "ai.koog:a2a-transport-client-jsonrpc-http", version.ref = "koog" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
